### ISSUE TITLE
Getting the error "Something went wrong calling the API: {"requestId":"ad5814b9d318ca9ddc435e221da4cfbf","date":"Thu, 09 Nov 2023 09:07:05 GMT","mscv":"4Z7J0fwuPxPczZcs.2","error":{"code":"badRequest","message":"The request is invalid.","innererror":{"code":"badOrMissingField","message":"The request does not contain a valid authority DID.","target":"authority"}}}"

### ISSUE THREAD

**Issue by adnpce** [Azure-Samples/VerifiedEmployeeIssuance#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
> Something went wrong calling the API: {"requestId":"ad5814b9d318ca9ddc435e221da4cfbf","date":"Thu, 09 Nov 2023 09:07:05 GMT","mscv":"4Z7J0fwuPxPczZcs.2","error":{"code":"badRequest","message":"The request is invalid.","innererror":{"code":"badOrMissingField","message":"The request does not contain a valid authority DID.","target":"authority"}}}

### Expected/desired behavior
> 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by GuidoBaijense** [comment]
Hi @adnpce . Have you checked the did-id that has to be set in the 'appsettings.json'?

**Comment by adnpce** [comment]
Hi Guido,

Yes, we checked the did-id.

Just to verify, the did-id is the below URL from the json file uploaded to our main website. I have attached the file for your reference. From this file, the below URL is the did-id I believe.

did:web:www.investinabudhabi.gov.ae

Thanks,
Sibin Sam



ADIO Confidential

**Comment by adnpce** [comment]
Hi Guido,

It seems to be working now. There was a mistake in the URL.



ADIO Confidential

From: Sibin Sam
Sent: Monday, November 13, 2023 2:38 PM
To: Azure-Samples/VerifiedEmployeeIssuance ***@***.***>; Azure-Samples/VerifiedEmployeeIssuance ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure-Samples/VerifiedEmployeeIssuance] Getting the error "Something went wrong calling the API: {"requestId":"ad5814b9d318ca9ddc435e221da4cfbf","date":"Thu, 09 Nov 2023 09:07:05 GMT","mscv":"4Z7J0fwuPxPczZcs.2","error":{"code":"badRequest","messa...

Hi Guido,

Yes, we checked the did-id.

Just to verify, the did-id is the below URL from the json file uploaded to our main website. I have attached the file for your reference. From this file, the below URL is the did-id I believe.

did:web:www.investinabudhabi.gov.ae

Thanks,
Sibin Sam

**Comment by GuidoBaijense** [comment]
Glad that it has been fixed. If you could also close this issue I'll be really happy :).
